version: 2
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/push:
          image: santannaflavia/mit-repository-flavinha:circleci-flavia 

workflows:
  example-workflow:
    jobs:
      - example-job